accounts:
  - name: alice
    coins: ["20000000token", "2000000000000000000000stake"]
  - name: bob
    coins: ["10000000token", "1000000000000000000000stake"]
  - name: terry
    coins: ["10000000token", "1000000000000000000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
