// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: energija/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the energija module's genesis state.
type GenesisState struct {
	SmartMeterList    []SmartMeter    `protobuf:"bytes,1,rep,name=smartMeterList,proto3" json:"smartMeterList"`
	EnergyStoreList   []EnergyStore   `protobuf:"bytes,2,rep,name=energyStoreList,proto3" json:"energyStoreList"`
	BuyOrderBookList  []BuyOrderBook  `protobuf:"bytes,3,rep,name=buyOrderBookList,proto3" json:"buyOrderBookList"`
	SellOrderBookList []SellOrderBook `protobuf:"bytes,4,rep,name=sellOrderBookList,proto3" json:"sellOrderBookList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a024f1dc4cad1909, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetSmartMeterList() []SmartMeter {
	if m != nil {
		return m.SmartMeterList
	}
	return nil
}

func (m *GenesisState) GetEnergyStoreList() []EnergyStore {
	if m != nil {
		return m.EnergyStoreList
	}
	return nil
}

func (m *GenesisState) GetBuyOrderBookList() []BuyOrderBook {
	if m != nil {
		return m.BuyOrderBookList
	}
	return nil
}

func (m *GenesisState) GetSellOrderBookList() []SellOrderBook {
	if m != nil {
		return m.SellOrderBookList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "kiprasdak.energija.energija.GenesisState")
}

func init() { proto.RegisterFile("energija/genesis.proto", fileDescriptor_a024f1dc4cad1909) }

var fileDescriptor_a024f1dc4cad1909 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0x84, 0x40,
	0x18, 0xc6, 0x75, 0x77, 0xe9, 0x30, 0x45, 0x7f, 0x24, 0x22, 0x5c, 0x9a, 0xa2, 0x4b, 0x5b, 0x87,
	0x11, 0xea, 0x1b, 0x08, 0x51, 0x87, 0x22, 0x48, 0x82, 0x28, 0x48, 0xb4, 0x1d, 0xcc, 0x5c, 0xf7,
	0x95, 0x99, 0x11, 0xf2, 0x5b, 0xf4, 0xb1, 0xf6, 0xb8, 0xc7, 0x4e, 0x11, 0xfa, 0x35, 0x3a, 0x84,
	0xa3, 0x8d, 0xbb, 0x2b, 0x78, 0x7b, 0xf0, 0xf1, 0xf9, 0xcd, 0xfb, 0xbc, 0x2f, 0xda, 0xa3, 0x53,
	0xca, 0x82, 0xf0, 0xdd, 0xb3, 0x02, 0x3a, 0xa5, 0x3c, 0xe4, 0x24, 0x61, 0x20, 0xc0, 0x18, 0x46,
	0x61, 0xc2, 0x3c, 0x3e, 0xf6, 0x22, 0xf2, 0xff, 0x87, 0x12, 0xa6, 0xa9, 0x42, 0x3c, 0xf6, 0x98,
	0x70, 0x63, 0x2a, 0x28, 0xab, 0x82, 0xe6, 0x50, 0x79, 0x52, 0x64, 0x2e, 0x17, 0xc0, 0x68, 0x6d,
	0x1e, 0x28, 0xd3, 0x4f, 0x33, 0x17, 0xd8, 0x98, 0x32, 0xd7, 0x07, 0x88, 0x6a, 0x1b, 0x37, 0x5c,
	0x3a, 0x99, 0xb4, 0xfd, 0xdd, 0x00, 0x02, 0x90, 0xd2, 0x2a, 0x55, 0xf5, 0xf5, 0xf8, 0xb7, 0x87,
	0x36, 0xae, 0xaa, 0xe1, 0x1d, 0xe1, 0x09, 0x6a, 0x3c, 0xa0, 0x4d, 0x39, 0xd7, 0x6d, 0x39, 0xd6,
	0x4d, 0xc8, 0xc5, 0xbe, 0x7e, 0xd4, 0x1f, 0xad, 0x9f, 0x9f, 0x90, 0x8e, 0x52, 0xc4, 0x51, 0x11,
	0x7b, 0x30, 0xfb, 0x3e, 0xd4, 0xee, 0x57, 0x20, 0xc6, 0x23, 0xda, 0xaa, 0x2a, 0x39, 0x65, 0x23,
	0xc9, 0xed, 0x49, 0xee, 0xa8, 0x93, 0x7b, 0xd9, 0x64, 0x6a, 0xf0, 0x2a, 0xc6, 0x78, 0x46, 0xdb,
	0x7e, 0x9a, 0xdd, 0x95, 0x75, 0x6d, 0x80, 0x48, 0xa2, 0xfb, 0x12, 0x7d, 0xda, 0x89, 0xb6, 0x17,
	0x42, 0x35, 0xbb, 0x05, 0x32, 0x5e, 0xd0, 0x4e, 0xb9, 0xcd, 0x65, 0xfa, 0x40, 0xd2, 0xcf, 0xba,
	0x17, 0xb2, 0x98, 0xaa, 0xf1, 0x6d, 0x94, 0x7d, 0x3d, 0xcb, 0xb1, 0x3e, 0xcf, 0xb1, 0xfe, 0x93,
	0x63, 0xfd, 0xb3, 0xc0, 0xda, 0xbc, 0xc0, 0xda, 0x57, 0x81, 0xb5, 0x27, 0x12, 0x84, 0xe2, 0x2d,
	0xf5, 0xc9, 0x2b, 0xc4, 0x96, 0x7a, 0xc8, 0x52, 0x37, 0xfe, 0x68, 0xa4, 0xc8, 0x12, 0xca, 0xfd,
	0x35, 0x79, 0xcf, 0x8b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x16, 0xc5, 0x03, 0x94, 0x02,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SellOrderBookList) > 0 {
		for iNdEx := len(m.SellOrderBookList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SellOrderBookList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.BuyOrderBookList) > 0 {
		for iNdEx := len(m.BuyOrderBookList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BuyOrderBookList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.EnergyStoreList) > 0 {
		for iNdEx := len(m.EnergyStoreList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EnergyStoreList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.SmartMeterList) > 0 {
		for iNdEx := len(m.SmartMeterList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SmartMeterList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SmartMeterList) > 0 {
		for _, e := range m.SmartMeterList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.EnergyStoreList) > 0 {
		for _, e := range m.EnergyStoreList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BuyOrderBookList) > 0 {
		for _, e := range m.BuyOrderBookList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SellOrderBookList) > 0 {
		for _, e := range m.SellOrderBookList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SmartMeterList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SmartMeterList = append(m.SmartMeterList, SmartMeter{})
			if err := m.SmartMeterList[len(m.SmartMeterList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyStoreList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnergyStoreList = append(m.EnergyStoreList, EnergyStore{})
			if err := m.EnergyStoreList[len(m.EnergyStoreList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyOrderBookList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyOrderBookList = append(m.BuyOrderBookList, BuyOrderBook{})
			if err := m.BuyOrderBookList[len(m.BuyOrderBookList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellOrderBookList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellOrderBookList = append(m.SellOrderBookList, SellOrderBook{})
			if err := m.SellOrderBookList[len(m.SellOrderBookList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
