// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: energija/smart_meter.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SmartMeter struct {
	Index       string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Production  int32  `protobuf:"varint,2,opt,name=production,proto3" json:"production,omitempty"`
	Consumption int32  `protobuf:"varint,3,opt,name=consumption,proto3" json:"consumption,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *SmartMeter) Reset()         { *m = SmartMeter{} }
func (m *SmartMeter) String() string { return proto.CompactTextString(m) }
func (*SmartMeter) ProtoMessage()    {}
func (*SmartMeter) Descriptor() ([]byte, []int) {
	return fileDescriptor_646104aa28f0f884, []int{0}
}
func (m *SmartMeter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SmartMeter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SmartMeter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SmartMeter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartMeter.Merge(m, src)
}
func (m *SmartMeter) XXX_Size() int {
	return m.Size()
}
func (m *SmartMeter) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartMeter.DiscardUnknown(m)
}

var xxx_messageInfo_SmartMeter proto.InternalMessageInfo

func (m *SmartMeter) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *SmartMeter) GetProduction() int32 {
	if m != nil {
		return m.Production
	}
	return 0
}

func (m *SmartMeter) GetConsumption() int32 {
	if m != nil {
		return m.Consumption
	}
	return 0
}

func (m *SmartMeter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*SmartMeter)(nil), "kiprasdak.energija.energija.SmartMeter")
}

func init() { proto.RegisterFile("energija/smart_meter.proto", fileDescriptor_646104aa28f0f884) }

var fileDescriptor_646104aa28f0f884 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0xcd, 0x4b, 0x2d,
	0x4a, 0xcf, 0xcc, 0x4a, 0xd4, 0x2f, 0xce, 0x4d, 0x2c, 0x2a, 0x89, 0xcf, 0x4d, 0x2d, 0x49, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xce, 0xce, 0x2c, 0x28, 0x4a, 0x2c, 0x4e, 0x49,
	0xcc, 0xd6, 0x83, 0xa9, 0x82, 0x33, 0x94, 0xda, 0x18, 0xb9, 0xb8, 0x82, 0x41, 0x5a, 0x7c, 0x41,
	0x3a, 0x84, 0x44, 0xb8, 0x58, 0x33, 0xf3, 0x52, 0x52, 0x2b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x20, 0x1c, 0x21, 0x39, 0x2e, 0xae, 0x82, 0xa2, 0xfc, 0x94, 0xd2, 0xe4, 0x92, 0xcc, 0xfc,
	0x3c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x24, 0x11, 0x21, 0x05, 0x2e, 0xee, 0xe4, 0xfc,
	0xbc, 0xe2, 0xd2, 0xdc, 0x02, 0xb0, 0x02, 0x66, 0xb0, 0x02, 0x64, 0x21, 0x90, 0x8a, 0x94, 0xd4,
	0xe2, 0xe4, 0xa2, 0x4c, 0x88, 0x0a, 0x16, 0xb0, 0xe9, 0xc8, 0x42, 0x4e, 0x1e, 0x27, 0x1e, 0xc9,
	0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e,
	0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x97, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97,
	0x9c, 0x9f, 0xab, 0x0f, 0xf7, 0x8a, 0x3e, 0xdc, 0xc3, 0x15, 0x08, 0x66, 0x49, 0x65, 0x41, 0x6a,
	0x71, 0x12, 0x1b, 0xd8, 0xdb, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x3e, 0x25, 0x7e,
	0x14, 0x01, 0x00, 0x00,
}

func (m *SmartMeter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SmartMeter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SmartMeter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintSmartMeter(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.Consumption != 0 {
		i = encodeVarintSmartMeter(dAtA, i, uint64(m.Consumption))
		i--
		dAtA[i] = 0x18
	}
	if m.Production != 0 {
		i = encodeVarintSmartMeter(dAtA, i, uint64(m.Production))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintSmartMeter(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSmartMeter(dAtA []byte, offset int, v uint64) int {
	offset -= sovSmartMeter(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SmartMeter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovSmartMeter(uint64(l))
	}
	if m.Production != 0 {
		n += 1 + sovSmartMeter(uint64(m.Production))
	}
	if m.Consumption != 0 {
		n += 1 + sovSmartMeter(uint64(m.Consumption))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovSmartMeter(uint64(l))
	}
	return n
}

func sovSmartMeter(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSmartMeter(x uint64) (n int) {
	return sovSmartMeter(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SmartMeter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSmartMeter
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SmartMeter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SmartMeter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmartMeter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSmartMeter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSmartMeter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Production", wireType)
			}
			m.Production = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmartMeter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Production |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consumption", wireType)
			}
			m.Consumption = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmartMeter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Consumption |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmartMeter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSmartMeter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSmartMeter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSmartMeter(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSmartMeter
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSmartMeter(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSmartMeter
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSmartMeter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSmartMeter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSmartMeter
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSmartMeter
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSmartMeter
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSmartMeter        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSmartMeter          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSmartMeter = fmt.Errorf("proto: unexpected end of group")
)
