// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: energija/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterSmartMeter struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Production  int32  `protobuf:"varint,2,opt,name=production,proto3" json:"production,omitempty"`
	Consumption int32  `protobuf:"varint,3,opt,name=consumption,proto3" json:"consumption,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgRegisterSmartMeter) Reset()         { *m = MsgRegisterSmartMeter{} }
func (m *MsgRegisterSmartMeter) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterSmartMeter) ProtoMessage()    {}
func (*MsgRegisterSmartMeter) Descriptor() ([]byte, []int) {
	return fileDescriptor_137e85d07cef0710, []int{0}
}
func (m *MsgRegisterSmartMeter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterSmartMeter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterSmartMeter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterSmartMeter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterSmartMeter.Merge(m, src)
}
func (m *MsgRegisterSmartMeter) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterSmartMeter) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterSmartMeter.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterSmartMeter proto.InternalMessageInfo

func (m *MsgRegisterSmartMeter) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterSmartMeter) GetProduction() int32 {
	if m != nil {
		return m.Production
	}
	return 0
}

func (m *MsgRegisterSmartMeter) GetConsumption() int32 {
	if m != nil {
		return m.Consumption
	}
	return 0
}

func (m *MsgRegisterSmartMeter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MsgRegisterSmartMeterResponse struct {
}

func (m *MsgRegisterSmartMeterResponse) Reset()         { *m = MsgRegisterSmartMeterResponse{} }
func (m *MsgRegisterSmartMeterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterSmartMeterResponse) ProtoMessage()    {}
func (*MsgRegisterSmartMeterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_137e85d07cef0710, []int{1}
}
func (m *MsgRegisterSmartMeterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterSmartMeterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterSmartMeterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterSmartMeterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterSmartMeterResponse.Merge(m, src)
}
func (m *MsgRegisterSmartMeterResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterSmartMeterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterSmartMeterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterSmartMeterResponse proto.InternalMessageInfo

type MsgRegisterEnergyStore struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgRegisterEnergyStore) Reset()         { *m = MsgRegisterEnergyStore{} }
func (m *MsgRegisterEnergyStore) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterEnergyStore) ProtoMessage()    {}
func (*MsgRegisterEnergyStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_137e85d07cef0710, []int{2}
}
func (m *MsgRegisterEnergyStore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterEnergyStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterEnergyStore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterEnergyStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterEnergyStore.Merge(m, src)
}
func (m *MsgRegisterEnergyStore) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterEnergyStore) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterEnergyStore.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterEnergyStore proto.InternalMessageInfo

func (m *MsgRegisterEnergyStore) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterEnergyStore) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MsgRegisterEnergyStoreResponse struct {
}

func (m *MsgRegisterEnergyStoreResponse) Reset()         { *m = MsgRegisterEnergyStoreResponse{} }
func (m *MsgRegisterEnergyStoreResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterEnergyStoreResponse) ProtoMessage()    {}
func (*MsgRegisterEnergyStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_137e85d07cef0710, []int{3}
}
func (m *MsgRegisterEnergyStoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterEnergyStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterEnergyStoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterEnergyStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterEnergyStoreResponse.Merge(m, src)
}
func (m *MsgRegisterEnergyStoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterEnergyStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterEnergyStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterEnergyStoreResponse proto.InternalMessageInfo

type MsgTokenizeEnergy struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgTokenizeEnergy) Reset()         { *m = MsgTokenizeEnergy{} }
func (m *MsgTokenizeEnergy) String() string { return proto.CompactTextString(m) }
func (*MsgTokenizeEnergy) ProtoMessage()    {}
func (*MsgTokenizeEnergy) Descriptor() ([]byte, []int) {
	return fileDescriptor_137e85d07cef0710, []int{4}
}
func (m *MsgTokenizeEnergy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTokenizeEnergy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTokenizeEnergy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTokenizeEnergy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTokenizeEnergy.Merge(m, src)
}
func (m *MsgTokenizeEnergy) XXX_Size() int {
	return m.Size()
}
func (m *MsgTokenizeEnergy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTokenizeEnergy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTokenizeEnergy proto.InternalMessageInfo

func (m *MsgTokenizeEnergy) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTokenizeEnergy) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgTokenizeEnergyResponse struct {
}

func (m *MsgTokenizeEnergyResponse) Reset()         { *m = MsgTokenizeEnergyResponse{} }
func (m *MsgTokenizeEnergyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTokenizeEnergyResponse) ProtoMessage()    {}
func (*MsgTokenizeEnergyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_137e85d07cef0710, []int{5}
}
func (m *MsgTokenizeEnergyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTokenizeEnergyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTokenizeEnergyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTokenizeEnergyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTokenizeEnergyResponse.Merge(m, src)
}
func (m *MsgTokenizeEnergyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTokenizeEnergyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTokenizeEnergyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTokenizeEnergyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterSmartMeter)(nil), "kiprasdak.energija.energija.MsgRegisterSmartMeter")
	proto.RegisterType((*MsgRegisterSmartMeterResponse)(nil), "kiprasdak.energija.energija.MsgRegisterSmartMeterResponse")
	proto.RegisterType((*MsgRegisterEnergyStore)(nil), "kiprasdak.energija.energija.MsgRegisterEnergyStore")
	proto.RegisterType((*MsgRegisterEnergyStoreResponse)(nil), "kiprasdak.energija.energija.MsgRegisterEnergyStoreResponse")
	proto.RegisterType((*MsgTokenizeEnergy)(nil), "kiprasdak.energija.energija.MsgTokenizeEnergy")
	proto.RegisterType((*MsgTokenizeEnergyResponse)(nil), "kiprasdak.energija.energija.MsgTokenizeEnergyResponse")
}

func init() { proto.RegisterFile("energija/tx.proto", fileDescriptor_137e85d07cef0710) }

var fileDescriptor_137e85d07cef0710 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0x39, 0x50, 0x8c, 0xcf, 0xc4, 0x84, 0x1a, 0x09, 0x42, 0x3c, 0x9b, 0x4e, 0x4c, 0x25,
	0x81, 0xc4, 0x41, 0x37, 0x13, 0x12, 0x97, 0x2e, 0x85, 0xc9, 0xad, 0x94, 0x97, 0x7a, 0x92, 0xf6,
	0x9a, 0xbb, 0x6b, 0x02, 0xce, 0x26, 0xae, 0x2c, 0xfe, 0x4f, 0x8e, 0x8c, 0x8e, 0x06, 0xfe, 0x11,
	0x43, 0xa1, 0xb5, 0x42, 0x83, 0xe2, 0x76, 0xf7, 0xfa, 0x7b, 0xdf, 0xf7, 0xfa, 0x5d, 0x1e, 0x54,
	0x30, 0x40, 0xe1, 0xb1, 0x27, 0xa7, 0xa5, 0xc6, 0x66, 0x28, 0xb8, 0xe2, 0x5a, 0x63, 0xc4, 0x42,
	0xe1, 0xc8, 0xa1, 0x33, 0x32, 0x93, 0x8f, 0xe9, 0xc1, 0x78, 0x23, 0x70, 0x6e, 0x49, 0xcf, 0x46,
	0x8f, 0x49, 0x85, 0xa2, 0xe7, 0x3b, 0x42, 0x59, 0xa8, 0x50, 0x68, 0x35, 0x38, 0x72, 0x05, 0x3a,
	0x8a, 0x8b, 0x1a, 0xd1, 0x49, 0xf3, 0xd8, 0x4e, 0xae, 0x1a, 0x05, 0x08, 0x05, 0x1f, 0x46, 0xae,
	0x62, 0x3c, 0xa8, 0x15, 0x75, 0xd2, 0x3c, 0xb4, 0x33, 0x15, 0x4d, 0x87, 0x13, 0x97, 0x07, 0x32,
	0xf2, 0xc3, 0x18, 0x28, 0xc5, 0x40, 0xb6, 0xb4, 0x24, 0x86, 0x28, 0x5d, 0xc1, 0x56, 0xc4, 0x41,
	0xac, 0x9f, 0x2d, 0x19, 0x57, 0x70, 0x99, 0x3b, 0x96, 0x8d, 0x32, 0xe4, 0x81, 0x44, 0xa3, 0x0f,
	0xd5, 0x0c, 0xd0, 0x5d, 0xfe, 0xcf, 0xa4, 0xa7, 0xb8, 0xc0, 0x1d, 0x83, 0x6f, 0xd8, 0x16, 0xb7,
	0x6d, 0x75, 0xa0, 0xf9, 0xaa, 0xa9, 0x6f, 0x17, 0x2a, 0x96, 0xf4, 0xfa, 0x7c, 0x84, 0x01, 0x7b,
	0xc6, 0x15, 0xb1, 0xc3, 0xb2, 0x0a, 0x65, 0xc7, 0xe7, 0x51, 0xa0, 0xd6, 0x39, 0xad, 0x6f, 0x46,
	0x03, 0x2e, 0xb6, 0x64, 0x12, 0x8f, 0xf6, 0xb4, 0x04, 0x25, 0x4b, 0x7a, 0xda, 0x0b, 0x01, 0x2d,
	0xe7, 0x65, 0xda, 0xe6, 0x8e, 0x17, 0x35, 0x73, 0x63, 0xab, 0xdf, 0xec, 0xdf, 0x93, 0x8c, 0xa3,
	0xbd, 0x12, 0x38, 0xcb, 0x0b, 0xba, 0xf3, 0x57, 0xcd, 0x4c, 0x53, 0xfd, 0xf6, 0x1f, 0x4d, 0xe9,
	0x24, 0x63, 0x38, 0xdd, 0x48, 0xde, 0xfc, 0x4d, 0xee, 0x27, 0x5f, 0xbf, 0xde, 0x8f, 0x4f, 0x9c,
	0xef, 0xee, 0xdf, 0xe7, 0x94, 0xcc, 0xe6, 0x94, 0x7c, 0xce, 0x29, 0x99, 0x2e, 0x68, 0x61, 0xb6,
	0xa0, 0x85, 0x8f, 0x05, 0x2d, 0x3c, 0x98, 0x1e, 0x53, 0x8f, 0xd1, 0xc0, 0x74, 0xb9, 0xdf, 0x4a,
	0xb5, 0x5b, 0xe9, 0x1a, 0x8e, 0xbf, 0x8f, 0x6a, 0x12, 0xa2, 0x1c, 0x94, 0xe3, 0xad, 0xec, 0x7c,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x62, 0xa0, 0xe4, 0xaa, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterSmartMeter(ctx context.Context, in *MsgRegisterSmartMeter, opts ...grpc.CallOption) (*MsgRegisterSmartMeterResponse, error)
	RegisterEnergyStore(ctx context.Context, in *MsgRegisterEnergyStore, opts ...grpc.CallOption) (*MsgRegisterEnergyStoreResponse, error)
	TokenizeEnergy(ctx context.Context, in *MsgTokenizeEnergy, opts ...grpc.CallOption) (*MsgTokenizeEnergyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterSmartMeter(ctx context.Context, in *MsgRegisterSmartMeter, opts ...grpc.CallOption) (*MsgRegisterSmartMeterResponse, error) {
	out := new(MsgRegisterSmartMeterResponse)
	err := c.cc.Invoke(ctx, "/kiprasdak.energija.energija.Msg/RegisterSmartMeter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterEnergyStore(ctx context.Context, in *MsgRegisterEnergyStore, opts ...grpc.CallOption) (*MsgRegisterEnergyStoreResponse, error) {
	out := new(MsgRegisterEnergyStoreResponse)
	err := c.cc.Invoke(ctx, "/kiprasdak.energija.energija.Msg/RegisterEnergyStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TokenizeEnergy(ctx context.Context, in *MsgTokenizeEnergy, opts ...grpc.CallOption) (*MsgTokenizeEnergyResponse, error) {
	out := new(MsgTokenizeEnergyResponse)
	err := c.cc.Invoke(ctx, "/kiprasdak.energija.energija.Msg/TokenizeEnergy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterSmartMeter(context.Context, *MsgRegisterSmartMeter) (*MsgRegisterSmartMeterResponse, error)
	RegisterEnergyStore(context.Context, *MsgRegisterEnergyStore) (*MsgRegisterEnergyStoreResponse, error)
	TokenizeEnergy(context.Context, *MsgTokenizeEnergy) (*MsgTokenizeEnergyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterSmartMeter(ctx context.Context, req *MsgRegisterSmartMeter) (*MsgRegisterSmartMeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSmartMeter not implemented")
}
func (*UnimplementedMsgServer) RegisterEnergyStore(ctx context.Context, req *MsgRegisterEnergyStore) (*MsgRegisterEnergyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEnergyStore not implemented")
}
func (*UnimplementedMsgServer) TokenizeEnergy(ctx context.Context, req *MsgTokenizeEnergy) (*MsgTokenizeEnergyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenizeEnergy not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterSmartMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterSmartMeter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterSmartMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiprasdak.energija.energija.Msg/RegisterSmartMeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterSmartMeter(ctx, req.(*MsgRegisterSmartMeter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterEnergyStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterEnergyStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterEnergyStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiprasdak.energija.energija.Msg/RegisterEnergyStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterEnergyStore(ctx, req.(*MsgRegisterEnergyStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TokenizeEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTokenizeEnergy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TokenizeEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiprasdak.energija.energija.Msg/TokenizeEnergy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TokenizeEnergy(ctx, req.(*MsgTokenizeEnergy))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kiprasdak.energija.energija.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSmartMeter",
			Handler:    _Msg_RegisterSmartMeter_Handler,
		},
		{
			MethodName: "RegisterEnergyStore",
			Handler:    _Msg_RegisterEnergyStore_Handler,
		},
		{
			MethodName: "TokenizeEnergy",
			Handler:    _Msg_TokenizeEnergy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "energija/tx.proto",
}

func (m *MsgRegisterSmartMeter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterSmartMeter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterSmartMeter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.Consumption != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Consumption))
		i--
		dAtA[i] = 0x18
	}
	if m.Production != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Production))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterSmartMeterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterSmartMeterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterSmartMeterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterEnergyStore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterEnergyStore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterEnergyStore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterEnergyStoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterEnergyStoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterEnergyStoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTokenizeEnergy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTokenizeEnergy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTokenizeEnergy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTokenizeEnergyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTokenizeEnergyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTokenizeEnergyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterSmartMeter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Production != 0 {
		n += 1 + sovTx(uint64(m.Production))
	}
	if m.Consumption != 0 {
		n += 1 + sovTx(uint64(m.Consumption))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterSmartMeterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterEnergyStore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterEnergyStoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTokenizeEnergy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgTokenizeEnergyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterSmartMeter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterSmartMeter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterSmartMeter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Production", wireType)
			}
			m.Production = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Production |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consumption", wireType)
			}
			m.Consumption = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Consumption |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterSmartMeterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterSmartMeterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterSmartMeterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterEnergyStore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterEnergyStore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterEnergyStore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterEnergyStoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterEnergyStoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterEnergyStoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTokenizeEnergy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTokenizeEnergy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTokenizeEnergy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTokenizeEnergyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTokenizeEnergyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTokenizeEnergyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
